services:
  app:
    container_name: todo_axum
    build: ./api/.
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: mysql://admin:c9j74_b2_01eMD@db:3306/todo
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:lts-ubi
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: c9j74_b2_01eMD
      MARIADB_DATABASE: todo
      MARIADB_ROOT_PASSWORD: root_c9j74_b2
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mariadb_data:
