[package]
name = "todo"
version = "0.1.0"
edition = "2024"

[dependencies]
# Backend
async-trait = "0.1"
axum = "0.8"
tokio = { version = "1.50", features = ["full"] }

# Structure → JSON ← Structure
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
sqlx = { version = "0.8", features = [
  "macros",
  "mysql",
  "runtime-tokio-native-tls",
  "tls-rustls"
] }

# Implements Errors
thiserror = "2.0"

# Environment configuration
clap = { version = "4.6.0", features = ["derive"] }
dotenv = "0.15"

# Validation
regex = "1.12"
tower = "0.5"
validator = { version = "0.20", features = ["derive"] }

# Hash
sha256 = "1.6"

# logging
tracing = "0.1"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.23", features = ["v4"] }

[dev-dependencies]

[profile.release]
opt-level = 3
lto = true
